### ISSUE TITLE
No horizontal scroll with trackpad

### ISSUE THREAD

**Issue by GiovanniFrigo** [BosNaufal/react-scrollbar#1]
When using a mac's trackpad, the user is pretty used to scroll horizontally using 2 fingers moving left or right., but the component does not react to this gesture. 
Hint: any other web component with `overflow-x: auto` or `overflow-x: scroll` does, so maybe you should try to use native DOM with custom css to achieve this.

**Comment by BosNaufal** [comment]
I'm Sorry, for now it can't horizontal scroll natively with two finger scrolling on trackpad. I still have no Idea about it. I've just checked it for the possibility to do it but it seems there's no way. 

But I would like to hear any advices~ :grin:
