### ISSUE TITLE
Uncaught TypeError: cb is not a function

### ISSUE THREAD

**Issue by usulpro** [BosNaufal/react-scrollbar#2]
Hi, it throws this when i clicking inside of scroll area

> Uncaught TypeError: cb is not a function
> calculateSize @ VM4301 build.js:27487
> invokeGuardedCallback @ VM4301 build.js:12760
> executeDispatch @ VM4301 build.js:12589
> executeDispatchesInOrder @ VM4301 build.js:12612
> executeDispatchesAndRelease @ VM4301 build.js:12046
> executeDispatchesAndReleaseTopLevel @ VM4301 build.js:12057
> forEachAccumulated @ VM4301 build.js:12903
> processEventQueue @ VM4301 build.js:12223
> runEventQueueInBatch @ VM4301 build.js:19029
> handleTopLevel @ VM4301 build.js:19040
> handleTopLevelImpl @ VM4301 build.js:23684
> perform @ VM4301 build.js:14691
> batchedUpdates @ VM4301 build.js:23601
> batchedUpdates @ VM4301 build.js:13868
> dispatchEvent @ VM4301 build.js:23761

why could it happens?

**Comment by BosNaufal** [comment]
Hi @UsulPro, I'm sorry I missed that thing:fearful:.
Thank you for giving me an issue BTW~ :grin:

You can contribute it or just waiting for my fixing....

**Comment by usulpro** [comment]
Thank you, i will wait))

**Comment by BosNaufal** [comment]
https://github.com/BosNaufal/react-scrollbar/pull/4
