### ISSUE TITLE
adding scrollYTo(position) function anytime soon

### ISSUE THREAD

**Issue by lc00** [BosNaufal/react-scrollbar#6]
Hi,
Awesome react stuff! 
 I'm working on a project with your library and trying to figure out how to add a scrollYTo(position) function.  Any tips would be greatly appreciated.

Thanks!

**Comment by usulpro** [comment]
Hi, @lc00!
I also want to have it.
I think it would be good to add it to this library. Probably first need to decide how exactly it should look

**Comment by BosNaufal** [comment]
Hey @lc00, @UsulPro,
It's a good Idea! :smile:  Please wait for my update ~ :grin:

**Comment by BosNaufal** [comment]
https://github.com/BosNaufal/react-scrollbar/commit/c57a8f84092c2a2a2c3463e822009f82a5436af5

**Comment by lc00** [comment]
Thanks for the update! I'll add this into my project 👍
