### ISSUE TITLE
Warning: Cb is not function

### ISSUE THREAD

**Issue by pionl** [BosNaufal/react-scrollbar#8]
Thank you for the package, just an error while scrolling. Would be safer to use typeof cb == "function" than cb ? cb(). Using Chrome

calculateSize   @   react-scrollbar.js:263

**Comment by BosNaufal** [comment]
Hey @pionl, Thank you for giving me an issue~

But I think It should has no any problem. But I've just made some [commit](https://github.com/BosNaufal/react-scrollbar/commit/0f05c77750d8f270a93cbfb38235aae60e9cf7e5). Please Check it out~

**Comment by pionl** [comment]
@BosNaufal Hi thanks for the fix, this should work. Will test later. 
Martin
